### PR TITLE
Max speech duration + bits per sample

### PR DESCRIPTION
**Pull request by b-med**
First of all, thank you for this wonderful work.

A small PR for two points :
1. Possibility to set a maximum duration of speech chunks (split in the last silence>~100ms, if any, otherwise force split)
2. Force `bits_per_sample=16` when saving audios. idk why it is saving with `25` even if it is set to `16` by default.

The code may be not very clean for now, I also kept some comments for easier review.
Cheers

### CODE REVIEW

**Comment by snakers4** [comment]
Hi,

Many thanks for your contribution.

> Possibility to set a maximum duration of speech chunks (split in the last silence>~100ms, if any, otherwise force split)

To better wrap our heads around why this is needed, can you please send an audio file you were testing this on? This will make testing much easier.

**Comment by b-med** [comment]
Unfortunately, I only tested it on private data I am afraid I can not share.
In our context, this was very important because we use big min_silence_duration_ms (2000) and speech_pad_ms (250) values resulting in some long chunks.
But in general, I believe this is very important, especially for production (eg. for downstream offline E2E ASR) :
- for servers with limited computational ressources 
- but also for any production context to control all the variables (we don't event want a 0.1% probability of crash because of a preventable issue)

**Comment by b-med** [comment]
Oh sorry, I was not speaking about the VAD cost (it is impressively efficient btw!).
It is rather about the cost/requirements of potential downstream tasks, eg. doing ASR on the speech segments produced by the VAD.
An example is that if the VAD produces, let's say, a 11s speech segment, but the maximum audio duration one deployed ASR API could handle is 10s. In this situation a "relatively smart" way to prevent producing speech segments longer than 10s is very interesting.

**Comment by snakers4** [comment]
I see now.
We will need to test. The chunking code is quite convoluted now.
In any case we avoided dealing with long non-interrupted speech for the lack of proper way to separate it.

> (split in the last silence>~100ms, if any, otherwise force split)

Your solution also seems to be a crutch, but we need to run some tests on real audios to test your code.

**Comment by adamnsandle** [comment]
Merged your PR. Thanks for your contribution!

**Pull request merged**
