### PR TITLE
Integration with microphone and webRTC module

### PR DESCRIPTION
**Pull request by Bontempogianpaolo1**
In this example, an integration with the microphone and the webRTC VAD has been done.  I used [this](https://github.com/mozilla/DeepSpeech-examples/tree/r0.8/mic_vad_streaming) as a draft.

### CODE REVIEW

**Comment by snakers4** [comment]
Hi,

Many thanks for your example!

Could you please add some minimal information about environment / installation instructions, i.e.:

- `requirements.txt` with your library versions or just some minimal info like `pip install lib=version` or same via conda;
- Some information about environment and any setup required (if any) on the computer this was tested on (i.e. sound drivers or similar);

As for the code it looks nice for an example as is, but in ideal world I would fix a couple of things (these are just a suggestion):

- Some of the imports are never used;
- Please note that `time_stamps =get_speech_ts(audio_float32, model,num_steps=4)` can be [tuned](https://github.com/snakers4/silero-vad#vad-parameter-fine-tuning) as well (or you can try using the adaptive method);
- Many libraries used (`np`, `wave`, `scipy`, `torch`, `torchaudio`) have kind of similar functionalities (i.e. array handling, resampling, loading and saving audio). Ideally in our examples we strive to minimize the dependencies as much as possible. This is by no means obligatory, but if you have time, please try removing redundant APIs (i.e. resampling / saving / loading - can be do via torchaudio for example, `np` calls can be replaced with torch in most of cases);

**Comment by Bontempogianpaolo1** [comment]
- requirements added in the README.md
- useless imports removed
- parameters of get_speech_ts can be tuned
- redundant APIs have been removed avoiding functions like resampling, saving, loading ( no time to find the best alternative between libraries)

**Comment by snakers4** [comment]
Nice!

**Comment by snakers4** [comment]
What I like about this - it is the first structured report on using the vad with the language it was not trained on, though italian is kind of similar to spanish 

Some people reportedly did this, but they did not return with any tangible tests / demos / metrics, either everything is ok or everything is not ok without details

**Comment by Bontempogianpaolo1** [comment]
Yeah, Agree. The possibility to upload small video on issues and readme is a new github feature. I hope to find a lot of instructions like this in the future. I mean, videos are very useful to understand the quality in real case scenarios for examples. Moreover, many people  don't know the metrics and they don't have time to read papers.

**Comment by snakers4** [comment]
Video is very cool
For a long time github has been lacking audio!
Is audio now supported?
Is there some doc / blog post about video?
I totally missed this feature!
Lack of audio / video in md is such a pain

**Comment by Bontempogianpaolo1** [comment]
I don't know about blogs or docs but probably you can find them somewhere. Anyway it's very easy! You just need to drag and drop your audio/video on the readme/issue editor! The only limit is about the size. In fact the file should not exceed 10MB

**Pull request merged**
