### PR TITLE
Added support for cuda tensors

### PR DESCRIPTION
**Pull request by ExtReMLapin**
See title, working with on a ASRD project, had to do this change to allow the use of CUDA tensors (stored on GPU), because by default it init on CPU. (implicit default arg)

### CODE REVIEW

**Comment by snakers4** [comment]
- Why import torch 2 times?
- Using CUDA if you have CUDA by default is not advisable, since VAD is not really designed to run on CUDA, probably makes sens to add a kwarg;

**Comment by ExtReMLapin** [comment]
>Why import torch 2 times?
Because i'm stupid

>Using CUDA if you have CUDA by default is not advisable, since VAD is not really designed to run on CUDA, probably makes sens to add a kwarg;

Alright, I'm trying to milk as much ms as I can, unless I'm missing something, it doesn't seem to use a lot of core, am I missing something ? Is there any plan to make it more multithreaded ?

**Comment by snakers4** [comment]
> Alright, I'm trying to milk as much ms as I can, unless I'm missing something, it doesn't seem to use a lot of core, am I missing something ? Is there any plan to make it more multithreaded ?

I takes <1 ms per chunk on 1 CPU thread
So unless you have some particularly bad CPU, makes little sense to use CUDA

**Comment by ExtReMLapin** [comment]
you're right, after editing the code, it seems that it was because we were reloading the model on each endpoint call 
What's quite strange is the very first takes 300ms and the second one takes more than one second.

I wouldn't be surprised if it was the first ... but the second... that's surprising.

**Pull request closed without merging**
