### PR TITLE
Fix bug with dimensionality edge case

### PR DESCRIPTION
**Pull request by vlajnaya-mol**
In "get_speech_ts" function, If "chunks" variable has shape of (1, X) then "run_function(model, chunks)" will return a tensor of shape (Y,), but two dimensional (1, Y) tensor is needed to complete next "torch.cat" operation

### CODE REVIEW

**Comment by snakers4** [comment]
Hi @vlajnaya-mol 

Does this edge case occur with ONNX models for batch size 1?

**Comment by vlajnaya-mol** [comment]
Hi @snakers4 

I found this issue using PyTorch model mentioned [here](https://github.com/snakers4/silero-vad/tree/master#vad), I didn't try the ONNX one yet.

**Comment by snakers4** [comment]
Yeah, I know the source of the problem - I used to have a similar issue with silero-models and it just looks like colleagues just reused my old code with a rogue `.squeeze` invocation. We will just fix it by re-uploading fixed models. As for using your patch, it's better to fix the root of the problem.

We will close this PR when  the issue is fixed.

**Comment by snakers4** [comment]
@vlajnaya-mol 

https://github.com/snakers4/silero-vad/pull/15

please re-check your case
but we have updated the model and everything should work now
if anything does not work please feel free to open another issue or PR

**Comment by vlajnaya-mol** [comment]
Yep, it's working now, thanks

**Pull request closed without merging**
