### PR TITLE
add a simple parallelization example

### PR DESCRIPTION
**Pull request by zzzacwork**

### CODE REVIEW

**Comment by snakers4** [comment]
@zzzacwork 

Many thanks for you example!

The only thing I would - add I would create separate objects per process.
The easiest way to do so would be using the custom process initializer.

https://superfastpython.com/processpoolexecutor-in-python/#Configure_the_Process_Initializer

**Comment by zzzacwork** [comment]
@snakers4 Thank you very the advice! I think  python multiple processing will use copy-on-write for global variables therefore the model object will actually be copied for each worker task therefore the result should be correct.  The initializer is still useful since it should keep the copied model object persistent across different worker tasks. However in my testing, it doesn't provide speed improvement compared to the previous version. Maybe I didn't do it correct.

**Comment by snakers4** [comment]
Typically ML accelerated libraries in python, like pytorch or onnx runtime, point to some internal C++ object. 

When you create a global python variable you most likely just create a pointer, which even when copied remains a pointer to some external object. So copying a pointer does not make sense.

Here it may not be a problem due to VAD being fast, but this is not a correct thiing to do.

Also not sure why you download the model into the same variables several times.

**Comment by zzzacwork** [comment]
Yeah, you are absolutely right, I tested it and it turns out the model is shared between different processes. As you said, the copy-on-write paradigm doesn't apply to pytorch objects. I changed it to use a global dict and initialize each pid with a separate model. Is this the best way to do this? Thanks.

**Comment by snakers4** [comment]
If I am not mistaken, the custom init function is executed in each process independently, hence not sure why you need the dict?

Please correct me if I am wrong.

**Comment by zzzacwork** [comment]
yeah, it is executed in each process independently, I add the dict so that the worker function can get the variable of the model. Are you aware of a better solution for this? I did some research but I cannot find it better way for the worker function to get access to that resource.

**Pull request merged**
